FROM node:18-alpine AS build
WORKDIR /app

COPY . .

RUN npm install

# Vite loads .env.production during this step
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
